import { useMemo, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { toast } from "sonner";
import { CalendarClock, Download, Handshake, MessageCircle, Plus, Search } from "lucide-react";
import { supabase } from "@/integrations/supabase/client";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";

type Etapa = "novo" | "qualificado" | "reuniao" | "proposta" | "piloto" | "contratado" | "perdido";
type Lead = { id: string; entidade: string; responsavel: string; cargo: string; telefone: string; email: string; municipio: string; uf: string; segmento: string; associados: number; veiculos: number; rotas_atuais: number; dificuldade: string; etapa: Etapa; proxima_acao_em: string | null; motivo_perda: string | null; observacoes: string | null; created_at: string };
const ETAPAS: { valor: Etapa; rotulo: string }[] = [{ valor: "novo", rotulo: "Novo contato" }, { valor: "qualificado", rotulo: "Qualificado" }, { valor: "reuniao", rotulo: "Reunião" }, { valor: "proposta", rotulo: "Proposta" }, { valor: "piloto", rotulo: "Piloto" }, { valor: "contratado", rotulo: "Contratado" }, { valor: "perdido", rotulo: "Perdido" }];

export function PainelParcerias() {
  const qc = useQueryClient();
  const [busca, setBusca] = useState("");
  const [filtro, setFiltro] = useState("todos");
  const [aberto, setAberto] = useState<string | null>(null);
  const [nota, setNota] = useState("");
  const leads = useQuery({ queryKey: ["admin-parcerias"], queryFn: async () => { const { data, error } = await supabase.from("parcerias_leads").select("*").order("created_at", { ascending: false }); if (error) throw error; return (data ?? []) as Lead[]; } });
  const interacoes = useQuery({ queryKey: ["admin-parcerias-interacoes", aberto], enabled: !!aberto, queryFn: async () => { const { data, error } = await supabase.from("parcerias_interacoes").select("id, tipo, resumo, created_at").eq("lead_id", aberto ?? "").order("created_at", { ascending: false }); if (error) throw error; return data ?? []; } });
  const atualizar = useMutation({ mutationFn: async ({ id, etapa, proxima, motivo }: { id: string; etapa: Etapa; proxima?: string; motivo?: string }) => { if (etapa === "perdido" && (!motivo || motivo.trim().length < 5)) throw new Error("Informe o motivo da perda."); const { error } = await supabase.from("parcerias_leads").update({ etapa, proxima_acao_em: proxima || null, motivo_perda: etapa === "perdido" ? (motivo ?? null) : null }).eq("id", id); if (error) throw error; }, onSuccess: () => { toast.success("Etapa atualizada."); void qc.invalidateQueries({ queryKey: ["admin-parcerias"] }); }, onError: (e: Error) => toast.error(e.message) });
  const registrar = useMutation({ mutationFn: async ({ id, resumo }: { id: string; resumo: string }) => { const { error } = await supabase.from("parcerias_interacoes").insert({ lead_id: id, tipo: "anotacao", resumo }); if (error) throw error; }, onSuccess: () => { setNota(""); toast.success("Interação registrada."); void qc.invalidateQueries({ queryKey: ["admin-parcerias-interacoes"] }); }, onError: (e: Error) => toast.error(e.message) });
  const lista = useMemo(() => (leads.data ?? []).filter((l) => (filtro === "todos" || l.etapa === filtro) && `${l.entidade} ${l.responsavel} ${l.municipio} ${l.uf}`.toLowerCase().includes(busca.toLowerCase())), [leads.data, filtro, busca]);
  const atrasados = (leads.data ?? []).filter((l) => l.proxima_acao_em && new Date(l.proxima_acao_em) < new Date() && !["contratado", "perdido"].includes(l.etapa)).length;
  const total = leads.data?.length ?? 0;
  const contratados = leads.data?.filter((l) => l.etapa === "contratado").length ?? 0;

  function exportar() { const linhas = [["Entidade", "Responsável", "Telefone", "E-mail", "Cidade", "UF", "Veículos", "Etapa", "Próxima ação"], ...lista.map((l) => [l.entidade, l.responsavel, l.telefone, l.email, l.municipio, l.uf, String(l.veiculos), l.etapa, l.proxima_acao_em ?? ""])]; const csv = linhas.map((r) => r.map((v) => `"${v.replaceAll('"', '""')}"`).join(",")).join("\n"); const a = document.createElement("a"); a.href = URL.createObjectURL(new Blob(["\uFEFF" + csv], { type: "text/csv;charset=utf-8" })); a.download = "parcerias-rotacerta.csv"; a.click(); URL.revokeObjectURL(a.href); }

  return <section className="mt-6 border border-border bg-card p-5">
    <div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="flex items-center gap-2 text-lg font-bold"><Handshake className="size-5" /> Parcerias institucionais</h2><p className="mt-1 text-sm text-muted-foreground">Funil do Programa Cooperativa Pioneira.</p></div><Button variant="outline" onClick={exportar} disabled={!lista.length}><Download /> Exportar CSV</Button></div>
    <div className="mt-5 grid gap-3 sm:grid-cols-3">{[["Oportunidades", total], ["Ações atrasadas", atrasados], ["Contratados", contratados]].map(([r, v]) => <div key={r} className="border-l-2 border-accent bg-secondary/50 p-4"><p className="text-xs text-muted-foreground">{r}</p><p className="mt-1 text-2xl font-bold">{v}</p></div>)}</div>
    <div className="mt-5 flex flex-wrap gap-3"><label className="flex min-w-64 flex-1 items-center gap-2 border border-border bg-background px-3"><Search className="size-4 text-muted-foreground" /><Input value={busca} onChange={(e) => setBusca(e.target.value)} placeholder="Buscar entidade, responsável ou cidade" className="border-0 shadow-none" /></label><Select value={filtro} onValueChange={setFiltro}><SelectTrigger className="w-48"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="todos">Todas as etapas</SelectItem>{ETAPAS.map((e) => <SelectItem key={e.valor} value={e.valor}>{e.rotulo}</SelectItem>)}</SelectContent></Select></div>
    <div className="mt-5 grid gap-3">{lista.map((lead) => <article key={lead.id} className="border border-border p-4"><div className="flex flex-wrap items-start gap-3"><div className="min-w-0 flex-1"><h3 className="font-bold">{lead.entidade}</h3><p className="text-sm text-muted-foreground">{lead.responsavel} · {lead.cargo} · {lead.municipio}/{lead.uf}</p><p className="mt-1 text-xs text-muted-foreground">{lead.associados} associados · {lead.veiculos} veículos · {lead.rotas_atuais} rotas</p></div><Select value={lead.etapa} onValueChange={(valor) => { const etapa = valor as Etapa; if (etapa === "perdido") { const motivo = window.prompt("Motivo da perda (obrigatório):") ?? ""; atualizar.mutate({ id: lead.id, etapa, motivo }); } else { atualizar.mutate({ id: lead.id, etapa }); } }}><SelectTrigger className="w-40"><SelectValue /></SelectTrigger><SelectContent>{ETAPAS.map((e) => <SelectItem key={e.valor} value={e.valor}>{e.rotulo}</SelectItem>)}</SelectContent></Select><Button size="sm" variant="outline" onClick={() => setAberto(aberto === lead.id ? null : lead.id)}>Detalhes</Button></div>{aberto === lead.id && <div className="mt-4 grid gap-5 border-t border-border pt-4 lg:grid-cols-2"><div className="text-sm"><p><strong>Contato:</strong> {lead.telefone} · {lead.email}</p><p className="mt-2"><strong>Dificuldade:</strong> {lead.dificuldade}</p><div className="mt-4 flex gap-2"><Input type="datetime-local" aria-label="Próxima ação" onChange={(e) => { if (e.target.value) atualizar.mutate({ id: lead.id, etapa: lead.etapa, proxima: new Date(e.target.value).toISOString() }); }} /><Button asChild variant="outline" size="icon"><a href={`https://wa.me/55${lead.telefone.replace(/\D/g, "")}`} target="_blank" rel="noopener noreferrer" title="Abrir WhatsApp"><MessageCircle /></a></Button></div>{lead.proxima_acao_em && <p className="mt-2 flex items-center gap-2 text-xs text-muted-foreground"><CalendarClock className="size-4" /> Próxima ação: {new Date(lead.proxima_acao_em).toLocaleString("pt-BR")}</p>}</div><div><div className="flex gap-2"><Textarea value={nota} onChange={(e) => setNota(e.target.value)} placeholder="Registrar ligação, reunião, objeção ou próximo passo" /><Button size="icon" disabled={nota.trim().length < 3 || registrar.isPending} onClick={() => registrar.mutate({ id: lead.id, resumo: nota.trim() })} title="Registrar interação"><Plus /></Button></div><ul className="mt-3 grid gap-2 text-xs">{(interacoes.data ?? []).map((i) => <li key={i.id} className="border-l-2 border-border pl-3"><p>{i.resumo}</p><time className="text-muted-foreground">{new Date(i.created_at).toLocaleString("pt-BR")}</time></li>)}</ul></div></div>}</article>)}{!leads.isLoading && lista.length === 0 && <p className="py-8 text-center text-sm text-muted-foreground">Nenhuma oportunidade encontrada.</p>}</div>
    <details className="mt-6 border-t border-border pt-4"><summary className="cursor-pointer text-sm font-semibold">Kit de abordagem do fundador</summary><div className="mt-4 grid gap-3 text-sm text-muted-foreground md:grid-cols-3"><div className="bg-secondary/50 p-4"><strong className="text-foreground">Abertura</strong><p className="mt-2">“Quero entender como vocês organizam demanda, escalas e prestação de contas hoje. Não é uma ligação para impor aplicativo.”</p></div><div className="bg-secondary/50 p-4"><strong className="text-foreground">Diagnóstico</strong><p className="mt-2">Pergunte sobre ocupação, ociosidade, canais de reserva, cobrança, conflitos e tempo gasto pela diretoria.</p></div><div className="bg-secondary/50 p-4"><strong className="text-foreground">Próximo passo</strong><p className="mt-2">Proponha demonstração apenas se houver aderência. O piloto começa pequeno, tem metas e não renova automaticamente.</p></div></div></details>
  </section>;
}